### PR TITLE
Widgets Upgrade to IPywidgets6

### PR DESCRIPTION
**Pull request by nontas**
#### Introduced Changes

* Upgrades `menpowidgets` to be compatible with `ipywidgets=6.0.0`
* Updates the widgets to take into account the landmarks change introduced by https://github.com/menpo/menpo/pull/675
* Defines `view_widget()` - a convenience function proposed by @jabooth (https://github.com/menpo/menpo/pull/753) which can be called with a `list` or `LazyList` of any Menpo objects and automatically tries to determine which widget to use. It is very handy, given that the number of widget functions has increased a lot.

#### Requirements

* Merge https://github.com/menpo/menpo/pull/766 and https://github.com/menpo/menpofit/pull/103 along with this PR

#### Open Questions

1. The only widgets from `menpowidgets.base` that cannot be incorporated in the `view_widget` method are `webcam_widget`, `plot_graph`, `save_matplotlib_figure`, `save_mayavi_figure`. However, what do we do with `visualize_patches` and `visualize_patch_appearance_model`? The problem is that their function signature is different than the rest of the widgets, since they expect a list of patches and the corresponding pointcloud(s) that will be used to visualize them.

2. `view_widget()` is currently defined only for the widgets in `menpowidgets.base`. Even though we could very naturally include the widgets of `menpowidgets.menpofitwidgets.base`, it is currently impossible due to the `MenpoMissingDependencyError` logic. I think we should find a way to have all the widgets under the same function. Or alternatively to have a secondary convenience function (maybe `visualize_objects` and `visualize_model`?). The same stands for `menpo3dwidgets`.

3. Can I assume that a 3D shape model is always `TriMesh`? Or it can also be `PointCloud`? This is important for the `visualize_shape_model_3d`. If we want to support both, I have to define two separate functions (similar to the fact that `visualize_shapes_3d` supports `PointCloud`, `PointGraph` and `LabelledPointUndirectedGraph`, but not `TriMesh` which is (will be) supported by `visualize_meshes`.

Any thoughts on these issues @jabooth @patricksnape ??

#### TODO

- [x] Decide how to add `menpofitwidgets` and `menpo3dwidgets` in a convenience function.
- [x] Update the docs after finishing all the above.

### CODE REVIEW

**Comment by nontas** [comment]
Needless to say that this includes lots of changes and I would really like more people to try it before it gets merged!

**Comment by patricksnape** [comment]
>> However, what do we do with visualize_patches and visualize_patch_appearance_model?

Why can't they stay as separate methods?

>> Even though we could very naturally include the widgets of menpowidgets.menpofitwidgets.base, it is currently impossible due to the MenpoMissingDependencyError logic. 

I don't understand what the problem is?
>> I think we should find a way to have all the widgets under the same function.

Why?

>>Can I assume that a 3D shape model is always TriMesh? Or it can also be PointCloud? 

It can definitely be a `PointCloud`.

**Comment by nontas** [comment]
1) Sure, we can keep them as separate methods.

2) The problem is that the `view_widget` method needs to import the corresponding classes from `menpo`, `menpofit` and `menpo3d` in order to check the provided objects. This means that the `MenpoMissingDependencyError` logic cannot be used anymore. For example, it will be impossible to use `menpo` and `menpowidgets` without having `menpofit` installed, since importing `view_widget` would simply fail to import the various `menpofit` classes.

3) I feel that unifying all widgets under the same method is a great idea since we get rid of the complexity of knowing which widget method to import/use based on the type of the objects. However, haveing most widgets under `view_widget` and additionally have several other widget methods that support some Menpo object seems even more confusing. It is easier to teach the users that all they need to visualize Menpo objects is a single method and there are also some additional convenience widgets, such as `webcam_widget`.

4) Fu**ing hell!! It's becoming a nightmare!!

**Comment by patricksnape** [comment]
2. We can work around but just not even checking for those classes if we hit the import error.
 3. I sort of disagree in a way. I understand the convenience function but it's also a big maintenance burden as users might expect everything to be visualizable. For the really core classes like shapes and images it seems fine but I feel like it's a bit of a stretch for things like PCAModels to be honest. I personally feel like view_widget should only handle Images and Shapes. What kind of list do I have that contains images and models? I just feel like this is a super leaky abstraction that causes more headaches than it solves given that nearly all objects have `view_widget` on them anyway.
  4. If it's really that much of a pain then just throw a `NotImplementedError` and make an issue that it should be supported.

**Comment by patricksnape** [comment]
Is this ready?

**Comment by nontas** [comment]
We are currently facing two major blockers:

* Our animation does not work any more
* The `force_draw()` method in `MayaviRenderer` does not work which makes `menpo3d` widgets incapable of refreshing the rendering.

Given the need to have a new release, we decided with @jabooth and @patricksnape to postpone these by:

* Making the animation buttons invisible.
* Removing `menpo3d` widgets from this PR.

I think this PR is now ready and can be merged. Of course it would be great if people tried it before merging, but I know that time is pressing...

Remember we need to merge https://github.com/menpo/menpo/pull/766 and https://github.com/menpo/menpofit/pull/103 together with this PR.

**Comment by patricksnape** [comment]
- [x] Saving figures doesn't work (it just saves whatever the original image was)
- [x]  
    ```
    menpowidgets.view_widget([menpo.io.import_builtin_asset.einstein_jpg(), 
                              menpo.io.import_builtin_asset.lenna_ljson()])
    ```
- [x] 
    ```python
    import menpofit
    aam = menpofit.aam.load_balanced_frontal_face_fitter()
    aam.wrapped_fitter.aam.view_shape_models_widget()
    ```

**Comment by nontas** [comment]
* Good catch! It is fixed now.
* It's because you pass in an image and a shape. This should work:
```
menpowidgets.view_widget([menpo.io.import_builtin_asset.einstein_jpg(), 
                          menpo.io.import_builtin_asset.lenna_png()])
```
* That works for me. Keep in mind that you need to checkout `nontas/widgets_upgrade` on `menpo` and `menpofit` (the branches have the same name in both repos).

**Comment by patricksnape** [comment]
I don't think `view_widget` is a very good name = it's much more confusing than the old `visualize_images` etc. At least `visualize_objects` would be better so it's clear that it is for a list. It wasn't clear to me that I couldn't just visualize whatever I wanted as well.

**Comment by nontas** [comment]
I don't mind renaming it to `visualize_objects`. It would be extremely difficult if not impossible to visualize a list of whatever objects. Maybe I should make it more clear in the doc. @jabooth any thoughts?

**Comment by patricksnape** [comment]
Maybe we can call it `visualize_objects` and then just fake versions of `visualize_images` etc that just alias `visualize_objects` - even with a deprecation warning - because this would be a huge breaking change otherwise.

**Comment by nontas** [comment]
Just to clarify, the old main functions (`visualize_images`, etc.) are still there in `base.py`. They are simply removed from the highest import level and called internally by `view_widget`.

**Comment by patricksnape** [comment]
So it seems to be OK to me now - but we are having trouble with travis

**Pull request merged**
